use std::collections::HashMap;

lazy_static::lazy_static! {

// Типы полей (имена)
pub static ref TYPES: HashMap<&'static str, HashMap<&'static str, &'static str>> = [
    ("en", HashMap::new()),
    ("ru", [
        ("NULL", "Тип.NULL"),
        ("0x01", "Тип.Неопределено"),
        ("0x02", "Тип.Булево"),
        ("0x03", "Тип.Число"),
        ("0x04", "Тип.Дата"),
        ("0x05", "Тип.Строка"),
        ("0x06", "Тип.Двоичный"),
        ("0x08", "Тип.Ссылка"),
    ].iter().cloned().collect()),
].iter().cloned().collect();

// Стандартные поля (имена)
pub static ref FIELDS: HashMap<&'static str, HashMap<&'static str, &'static str>> = [
    ("en", HashMap::new()),
    ("ru", [
        ("_", ""),
        ("_AccountCtRRef", "СчетКт"),
        ("_AccountDtRRef", "СчетДт"),
        ("_AccountRRef", "Счет"),
        ("_Active", "Активность"),
        ("_BaseAsAct", "ПериодДействияБазовый"),
        ("_BaseCKBaseCK", "ВидРасчета"),
        ("_BusinessProcess", "БизнесПроцесс"),
        ("_Code", "Код"),
        ("_Completed", "Завершен"),
        ("_Correspond", "ВидДвижения"),
        ("_Date_Time", "Дата"),
        ("_Description", "Наименование"),
        ("_DimHash", "ХэшИзмерений"),
        ("_DimIsMetadata", "Предопределенное"),
        ("_DimKindRRef", "ВидСубконто"),
        ("_DisplacedCKDisplCK", "ВидРасчета"),
        ("_DocumentRRef", "Документ"),
        ("_DocumentTRef", "ВидДокумента"),
        ("_EDHash", "ХэшПроводки"),
        ("_EDHashCt", "ХэшПроводкиКт"),
        ("_EDHashDt", "ХэшПроводкиДт"),
        ("_EnumOrder", "Порядок"),
        ("_Executed", "Выполнена"),
        ("_Folder", "ЭтоГруппа"),
        ("_HeadTaskRRef", "ВедущаяЗадача"),
        ("_IDRRef", "Ссылка"),
        ("_IDTRef", "ВидСсылки"),
        ("_KeyField", "КлючЗаписи"),
        ("_Kind", "Вид"),
        ("_KindAt", "ВидСубконто"),
        ("_KindCt", "ВидСубконтоКт"),
        ("_KindDt", "ВидСубконтоДт"),
        ("_KindRRef", "Вид"),
        ("_KindSubconto", "ВидСубконто"),
        ("_KindSubcontoCt", "ВидСубконтоКт"),
        ("_KindSubcontoDt", "ВидСубконтоДт"),
        ("_LeadingCKLeadingCK", "ВидРасчета"),
        ("_LineNo", "НомерСтроки"),
        ("_Marked", "ПометкаУдаления"),
        ("_Name", "Наименование"),
        ("_Number", "Номер"),
        ("_NumberPrefix", "Префикс"),
        ("_OffBalance", "Забалансовый"),
        ("_OrderField", "Порядок"),
        ("_OwnerID", "Владелец"),
        ("_ParentIDRRef", "Родитель"),
        ("_Period", "Период"),
        ("_PeriodAdjustment", "УточнениеПериода"),
        ("_Point", "ТочкаМаршрута"),
        ("_Posted", "Проведен"),
        ("_PredefinedID", "Предопределенное"),
        ("_ReceivedNo", "НомерПринятого"),
        ("_RecorderRRef", "Регистратор"),
        ("_RecorderTRef", "ВидРегистратора"),
        ("_RecordKey", "КлючЗаписи"),
        ("_RecordKind", "ВидДвижения"),
        ("_RoutePointOrder", "Порядок"),
        ("_SentNo", "НомерОтправленного"),
        ("_Splitter", "Разделитель"),
        ("_Started", "Стартован"),
        ("_TurnoverOnly", "ТолькоОбороты"),
        ("_Type", "ТипЗначения"),
        ("_Value", "Значение"),
        ("_ValueAt", "Субконто"),
        ("_ValueCt", "СубконтоКт"),
        ("_ValueDt", "СубконтоДт"),
        ("_ValueSubconto", "Субконто"),
        ("_ValueSubcontoCt", "СубконтоКт"),
        ("_ValueSubcontoDt", "СубконтоДт"),
        ("_Version", "Версия"),
    ].iter().cloned().collect()),
].iter().cloned().collect();

// Стандартные поля (синонимы)
pub static ref FIELD_SYNONYMS: HashMap<&'static str, HashMap<&'static str, &'static str>> = [
    ("_", [("ru", "")].iter().cloned().collect()),
    ("_AccountCtRRef", [("ru", "Счет по кредиту")].iter().cloned().collect()),
    ("_AccountDtRRef", [("ru", "Счет по дебету")].iter().cloned().collect()),
    ("_AccountRRef", [("ru", "Счет")].iter().cloned().collect()),
    ("_Active", [("ru", "Активность")].iter().cloned().collect()),
    ("_BaseAsAct", [("ru", "Использует период действия")].iter().cloned().collect()),
    ("_BaseCKBaseCK", [("ru", "ВидРасчета")].iter().cloned().collect()),
    ("_BusinessProcess", [("ru", "Бизнес-процесс")].iter().cloned().collect()),
    ("_Code", [("ru", "Код")].iter().cloned().collect()),
    ("_Completed", [("ru", "Завершен")].iter().cloned().collect()),
    ("_Correspond", [("ru", "ВидДвижения")].iter().cloned().collect()),
    ("_Date_Time", [("ru", "Дата")].iter().cloned().collect()),
    ("_Description", [("ru", "Наименование")].iter().cloned().collect()),
    ("_DimHash", [("ru", "Хэш изм")].iter().cloned().collect()),
].iter().cloned().collect();

}
