use crate::HashMap;

lazy_static::lazy_static! {

// Типы полей (имена)
pub static ref TYPES: HashMap<&'static str, HashMap<&'static str, &'static str>> = [
    ("en", HashMap::new()),
    ("ru", [
        ("NULL", "Тип.NULL"),
        ("0x01", "Тип.Неопределено"),
        ("0x02", "Тип.Булево"),
        ("0x03", "Тип.Число"),
        ("0x04", "Тип.Дата"),
        ("0x05", "Тип.Строка"),
        ("0x06", "Тип.Двоичный"),
        ("0x08", "Тип.Ссылка"),
    ].iter().cloned().collect()),
].iter().cloned().collect();

// Стандартные поля (имена)
pub static ref FIELDS: HashMap<&'static str, HashMap<&'static str, &'static str>> = [
    ("en", HashMap::new()),
    ("ru", [
        ("_", ""),
        ("_AccountCtRRef", "СчетКт"),
        ("_AccountDtRRef", "СчетДт"),
        ("_AccountRRef", "Счет"),
        ("_Active", "Активность"),
        ("_BaseAsAct", "ПериодДействияБазовый"),
        ("_BaseCKBaseCK", "ВидРасчета"),
        ("_BusinessProcess", "БизнесПроцесс"),
        ("_Code", "Код"),
        ("_Completed", "Завершен"),
        ("_Correspond", "ВидДвижения"),
        ("_Date_Time", "Дата"),
        ("_Description", "Наименование"),
        ("_DimHash", "ХэшИзмерений"),
        ("_DimIsMetadata", "Предопределенное"),
        ("_DimKindRRef", "ВидСубконто"),
        ("_DisplacedCKDisplCK", "ВидРасчета"),
        ("_DocumentRRef", "Документ"),
        ("_DocumentTRef", "ВидДокумента"),
        ("_EDHash", "ХэшПроводки"),
        ("_EDHashCt", "ХэшПроводкиКт"),
        ("_EDHashDt", "ХэшПроводкиДт"),
        ("_EnumOrder", "Порядок"),
        ("_Executed", "Выполнена"),
        ("_Folder", "ЭтоГруппа"),
        ("_HeadTaskRRef", "ВедущаяЗадача"),
        ("_IDRRef", "Ссылка"),
        ("_IDTRef", "ВидСсылки"),
        ("_KeyField", "КлючЗаписи"),
        ("_Kind", "Вид"),
        ("_KindAt", "ВидСубконто"),
        ("_KindCt", "ВидСубконтоКт"),
        ("_KindDt", "ВидСубконтоДт"),
        ("_KindRRef", "Вид"),
        ("_KindSubconto", "ВидСубконто"),
        ("_KindSubcontoCt", "ВидСубконтоКт"),
        ("_KindSubcontoDt", "ВидСубконтоДт"),
        ("_LeadingCKLeadingCK", "ВидРасчета"),
        ("_LineNo", "НомерСтроки"),
        ("_Marked", "ПометкаУдаления"),
        ("_Name", "Наименование"),
        ("_Number", "Номер"),
        ("_NumberPrefix", "Префикс"),
        ("_OffBalance", "Забалансовый"),
        ("_OrderField", "Порядок"),
        ("_OwnerID", "Владелец"),
        ("_ParentIDRRef", "Родитель"),
        ("_Period", "Период"),
        ("_PeriodAdjustment", "УточнениеПериода"),
        ("_Point", "ТочкаМаршрута"),
        ("_Posted", "Проведен"),
        ("_PredefinedID", "Предопределенное"),
        ("_ReceivedNo", "НомерПринятого"),
        ("_RecorderRRef", "Регистратор"),
        ("_RecorderTRef", "ВидРегистратора"),
        ("_RecordKey", "КлючЗаписи"),
        ("_RecordKind", "ВидДвижения"),
        ("_RoutePointOrder", "Порядок"),
        ("_SentNo", "НомерОтправленного"),
        ("_Splitter", "Разделитель"),
        ("_Started", "Стартован"),
        ("_TurnoverOnly", "ТолькоОбороты"),
        ("_Type", "ТипЗначения"),
        ("_Value", "Значение"),
        ("_ValueAt", "Субконто"),
        ("_ValueCt", "СубконтоКт"),
        ("_ValueDt", "СубконтоДт"),
        ("_ValueSubconto", "Субконто"),
        ("_ValueSubcontoCt", "СубконтоКт"),
        ("_ValueSubcontoDt", "СубконтоДт"),
        ("_Version", "Версия"),
        // low case for PGSQL
        ("_accountctrref", "СчетКт"),
        ("_accountdtrref", "СчетДт"),
        ("_accountrref", "Счет"),
        ("_active", "Активность"),
        ("_baseasact", "ПериодДействияБазовый"),
        ("_baseckbaseck", "ВидРасчета"),
        ("_businessprocess", "БизнесПроцесс"),
        ("_code", "Код"),
        ("_completed", "Завершен"),
        ("_correspond", "ВидДвижения"),
        ("_date_time", "Дата"),
        ("_description", "Наименование"),
        ("_dimhash", "ХэшИзмерений"),
        ("_dimismetadata", "Предопределенное"),
        ("_dimkindrref", "ВидСубконто"),
        ("_displacedckdisplck", "ВидРасчета"),
        ("_documentrref", "Документ"),
        ("_documenttref", "ВидДокумента"),
        ("_edhash", "ХэшПроводки"),
        ("_edhashct", "ХэшПроводкиКт"),
        ("_edhashdt", "ХэшПроводкиДт"),
        ("_enumorder", "Порядок"),
        ("_executed", "Выполнена"),
        ("_folder", "ЭтоГруппа"),
        ("_headtaskrref", "ВедущаяЗадача"),
        ("_idrref", "Ссылка"),
        ("_idtref", "ВидСсылки"),
        ("_keyfield", "КлючЗаписи"),
        ("_kind", "Вид"),
        ("_kindat", "ВидСубконто"),
        ("_kindct", "ВидСубконтоКт"),
        ("_kinddt", "ВидСубконтоДт"),
        ("_kindrref", "Вид"),
        ("_kindsubconto", "ВидСубконто"),
        ("_kindsubcontoct", "ВидСубконтоКт"),
        ("_kindsubcontodt", "ВидСубконтоДт"),
        ("_leadingckleadingck", "Видрасчета"),
        ("_lineno", "НомерСтроки"),
        ("_marked", "ПометкаУдаления"),
        ("_name", "Наименование"),
        ("_number", "Номер"),
        ("_numberprefix", "Префикс"),
        ("_offbalance", "Забалансовый"),
        ("_orderfield", "Порядок"),
        ("_ownerid", "Владелец"),
        ("_parentidrref", "Родитель"),
        ("_period", "Период"),
        ("_periodadjustment", "УточнениеПериода"),
        ("_point", "ТочкаМаршрута"),
        ("_posted", "Проведен"),
        ("_predefinedid", "Предопределенное"),
        ("_receivedno", "НомерПринятого"),
        ("_recorderrref", "Регистратор"),
        ("_recordertref", "ВидРегистратора"),
        ("_recordkey", "КлючЗаписи"),
        ("_recordkind", "ВидДвижения"),
        ("_routepointorder", "Порядок"),
        ("_sentno", "НомерОтправленного"),
        ("_splitter", "Разделитель"),
        ("_started", "Стартован"),
        ("_turnoveronly", "ТолькоОбороты"),
        ("_type", "ТипЗначения"),
        ("_value", "Значение"),
        ("_valueat", "Субконто"),
        ("_valuect", "СубконтоКт"),
        ("_valuedt", "СубконтоДт"),
        ("_valuesubconto", "Субконто"),
        ("_valuesubcontoct", "СубконтоКт"),
        ("_valuesubcontodt", "СубконтоДт"),
        ("_version", "Версия"),
    ].iter().cloned().collect()),
].iter().cloned().collect();

// Стандартные поля (синонимы)
pub static ref FIELD_SYNONYMS: HashMap<&'static str, HashMap<&'static str, &'static str>> = [
    ("_", [("ru", "")].iter().cloned().collect()),
    ("_AccountCtRRef", [("ru", "Счет по кредиту")].iter().cloned().collect()),
    ("_AccountDtRRef", [("ru", "Счет по дебету")].iter().cloned().collect()),
    ("_AccountRRef", [("ru", "Счет")].iter().cloned().collect()),
    ("_Active", [("ru", "Активность")].iter().cloned().collect()),
    ("_BaseAsAct", [("ru", "Использует период действия")].iter().cloned().collect()),
    ("_BaseCKBaseCK", [("ru", "ВидРасчета")].iter().cloned().collect()),
    ("_BusinessProcess", [("ru", "Бизнес-процесс")].iter().cloned().collect()),
    ("_Code", [("ru", "Код")].iter().cloned().collect()),
    ("_Completed", [("ru", "Завершен")].iter().cloned().collect()),
    ("_Correspond", [("ru", "ВидДвижения")].iter().cloned().collect()),
    ("_Date_Time", [("ru", "Дата")].iter().cloned().collect()),
    ("_Description", [("ru", "Наименование")].iter().cloned().collect()),
    ("_DimHash", [("ru", "Хэш изм")].iter().cloned().collect()),
    // low case for PGSQL
    ("_accountctrref", [("ru", "Счет по кредиту")].iter().cloned().collect()),
    ("_accountdtrref", [("ru", "Счет по дебету")].iter().cloned().collect()),
    ("_accountrref", [("ru", "Счет")].iter().cloned().collect()),
    ("_active", [("ru", "Активность")].iter().cloned().collect()),
    ("_baseasact", [("ru", "Использует период действия")].iter().cloned().collect()),
    ("_baseckbaseck", [("ru", "ВидРасчета")].iter().cloned().collect()),
    ("_businessprocess", [("ru", "Бизнес-процесс")].iter().cloned().collect()),
    ("_code", [("ru", "Код")].iter().cloned().collect()),
    ("_completed", [("ru", "Завершен")].iter().cloned().collect()),
    ("_correspond", [("ru", "ВидДвижения")].iter().cloned().collect()),
    ("_date_time", [("ru", "Дата")].iter().cloned().collect()),
    ("_description", [("ru", "Наименование")].iter().cloned().collect()),
    ("_dimhash", [("ru", "Хэш изм")].iter().cloned().collect()),
].iter().cloned().collect();

}
